import React, { useEffect, useRef } from 'react';
import Reveal from 'reveal.js';
import { PresentationData, RevealTheme, THEME_URLS } from '../types';
import { ArrowLeft, Download, Maximize2 } from 'lucide-react';

interface PresentationViewProps {
  data: PresentationData;
  theme: RevealTheme;
  onClose: () => void;
}

const PresentationView: React.FC<PresentationViewProps> = ({ data, theme, onClose }) => {
  const revealRef = useRef<Reveal.Api | null>(null);
  const deckRef = useRef<HTMLDivElement>(null);

  // Effect to handle Theme switching
  useEffect(() => {
    const themeLink = document.getElementById('reveal-theme') as HTMLLinkElement;
    if (themeLink) {
      themeLink.href = THEME_URLS[theme];
    }
  }, [theme]);

  // Effect to initialize Reveal.js
  useEffect(() => {
    if (deckRef.current) {
      // We need a small timeout to ensure the DOM is ready for Reveal to measure
      const initReveal = async () => {
        // If there is an existing instance, we might need to destroy it or just re-sync.
        // However, reveal.js doesn't support re-initialization on the same DOM easily without full reload.
        // Since this component mounts freshly when entering "presentation mode", we should be safe.
        
        const deck = new Reveal(deckRef.current, {
          hash: false, // Disable hash to avoid routing conflicts
          embedded: false, // Full window mode inside the component container logic
          controls: true,
          progress: true,
          center: true,
          transition: 'slide', // none/fade/slide/convex/concave/zoom
          backgroundTransition: 'fade',
        });

        await deck.initialize();
        revealRef.current = deck;
      };

      initReveal();

      return () => {
        try {
          if (revealRef.current) {
            revealRef.current.destroy();
            revealRef.current = null;
          }
        } catch (e) {
          console.warn("Reveal destroy warning:", e);
        }
      };
    }
  }, []);

  const getImageUrl = (query?: string, index?: number) => {
    if (!query) return `https://picsum.photos/1920/1080?random=${index}`;
    // Simple mapping to unpslash source or similar for better relevance if possible, 
    // otherwise fallback to picsum with a seed.
    // Using picsum with seed for stability.
    return `https://picsum.photos/seed/${query.replace(/\s/g, '')}${index}/1920/1080`;
  };

  return (
    <div className="fixed inset-0 z-50 bg-black">
      {/* Toolbar overlay */}
      <div className="absolute top-4 left-4 z-[100] flex gap-2 pointer-events-auto">
        <button 
          onClick={onClose}
          className="flex items-center gap-2 px-4 py-2 bg-neutral-900/80 hover:bg-neutral-800 text-white rounded-full backdrop-blur-sm transition-all border border-neutral-700"
        >
          <ArrowLeft size={18} />
          <span>Exit</span>
        </button>
        <div className="px-4 py-2 bg-neutral-900/80 text-neutral-400 rounded-full backdrop-blur-sm border border-neutral-700 text-sm font-medium">
          {data.topic}
        </div>
      </div>

      <div className="absolute bottom-4 right-4 z-[100] pointer-events-auto text-neutral-500 text-xs">
        Using Gemini 2.5 Flash & Reveal.js
      </div>

      {/* Reveal.js Container */}
      <div className="reveal" ref={deckRef}>
        <div className="slides">
          {/* Title Slide */}
          <section data-background-gradient="linear-gradient(to bottom right, #2c3e50, #000000)">
            <h1 className="r-fit-text">{data.title}</h1>
            <h3 className="text-neutral-400 font-light">{data.subtitle}</h3>
            <p className="text-sm mt-12 opacity-50">Generated by InstantDeck AI</p>
          </section>

          {/* Generated Slides */}
          {data.slides.map((slide, index) => (
            <section key={index} data-background-image={getImageUrl(slide.imageQuery, index)} data-background-opacity="0.3">
              <div className="bg-black/60 p-8 rounded-xl backdrop-blur-sm border border-white/10 shadow-2xl">
                <h2 className="text-4xl font-bold mb-8 text-white drop-shadow-lg border-b border-white/20 pb-4">{slide.title}</h2>
                <ul className="space-y-4 text-left text-2xl text-neutral-100">
                  {slide.content.map((point, idx) => (
                    <li key={idx} className="fragment fade-up pl-2 border-l-4 border-blue-500/50 ml-4">
                       {point}
                    </li>
                  ))}
                </ul>
              </div>
              {slide.notes && (
                <aside className="notes">
                  {slide.notes}
                </aside>
              )}
            </section>
          ))}

          {/* End Slide */}
          <section data-background-color="#000">
            <h2>Thank You</h2>
            <p>Any questions?</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default PresentationView;